# Generated by Django 3.1.8 on 2021-09-01 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Database',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('authors', models.CharField(max_length=1000)),
                ('identifier', models.CharField(max_length=32)),
                ('DOI', models.CharField(max_length=32)),
                ('container_title', models.CharField(blank=True, max_length=1000, null=True)),
                ('publisher', models.CharField(default='', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('language', models.CharField(choices=[('ja', 'Japanese'), ('en', 'English')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Figure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddConstraint(
            model_name='term',
            constraint=models.UniqueConstraint(fields=('name', 'language'), name='term_unique'),
        ),
        migrations.AddField(
            model_name='tag',
            name='synonyms',
            field=models.ManyToManyField(blank=True, related_name='tags_synonyms', to='starrydata.Term'),
        ),
        migrations.AddField(
            model_name='tag',
            name='term_en',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tags_en', to='starrydata.term'),
        ),
        migrations.AddField(
            model_name='tag',
            name='term_ja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tags_ja', to='starrydata.term'),
        ),
        migrations.AddField(
            model_name='sample',
            name='paper',
            field=models.ManyToManyField(to='starrydata.Paper'),
        ),
        migrations.AddField(
            model_name='paper',
            name='database',
            field=models.ManyToManyField(to='starrydata.Database'),
        ),
        migrations.AddField(
            model_name='node',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='starrydata.node'),
        ),
        migrations.AddField(
            model_name='node',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='starrydata.tag'),
        ),
        migrations.AddField(
            model_name='figure',
            name='paper',
            field=models.ManyToManyField(to='starrydata.Paper'),
        ),
        migrations.AddConstraint(
            model_name='node',
            constraint=models.UniqueConstraint(fields=('tag', 'parent'), name='tag_unique'),
        ),
    ]
