# Generated by Django 3.2.4 on 2021-06-24 00:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('starrydata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyenthesisMethodTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='fabricationprocess',
            name='parent_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='starrydata.fabricationprocess'),
        ),
        migrations.CreateModel(
            name='SyenthesisMethodTagTreeNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('parent_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='starrydata.syenthesismethodtagtreenode')),
                ('tag_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='starrydata.syenthesismethodtag')),
            ],
        ),
    ]
