# Generated by Django 3.2.4 on 2021-06-24 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('starrydata', '0002_auto_20210624_0025'),
    ]

    operations = [
        migrations.RenameField(
            model_name='syenthesismethodtagtreenode',
            old_name='parent_id',
            new_name='parent',
        ),
        migrations.RenameField(
            model_name='syenthesismethodtagtreenode',
            old_name='tag_id',
            new_name='tag',
        ),
    ]
