# Generated by Django 3.2.4 on 2021-06-24 00:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('starrydata', '0003_auto_20210624_0037'),
    ]

    operations = [
        migrations.RenameField(
            model_name='syenthesismethodtagtreenode',
            old_name='parent',
            new_name='parent_id',
        ),
        migrations.RenameField(
            model_name='syenthesismethodtagtreenode',
            old_name='tag',
            new_name='tag_id',
        ),
        migrations.AlterField(
            model_name='syenthesismethodtagtreenode',
            name='parent_id',
            field=models.ForeignKey(blank=True, db_column='parent_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='starrydata.syenthesismethodtagtreenode'),
        ),
        migrations.AlterField(
            model_name='syenthesismethodtagtreenode',
            name='tag_id',
            field=models.ForeignKey(db_column='tag_id', on_delete=django.db.models.deletion.CASCADE, to='starrydata.syenthesismethodtag'),
        ),
    ]
