# Generated by Django 3.2.4 on 2021-06-24 01:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('starrydata', '0004_auto_20210624_0054'),
    ]

    operations = [
        migrations.CreateModel(
            name='SynthesisMethodTagTreeNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='starrydata.synthesismethodtagtreenode')),
            ],
        ),
        migrations.RenameModel(
            old_name='SyenthesisMethodTag',
            new_name='SynthesisMethodTag',
        ),
        migrations.DeleteModel(
            name='SyenthesisMethodTagTreeNode',
        ),
        migrations.AddField(
            model_name='synthesismethodtagtreenode',
            name='synthesis_method_tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='starrydata.synthesismethodtag'),
        ),
    ]
