# Generated by Django 3.2.4 on 2021-06-29 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starrydata', '0006_database'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('authors', models.CharField(max_length=1000)),
                ('identifier', models.CharField(max_length=32)),
                ('DOI', models.CharField(max_length=32)),
                ('database', models.ManyToManyField(to='starrydata.Database')),
            ],
        ),
    ]
