# Generated by Django 3.2.4 on 2021-06-29 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starrydata', '0007_paper'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paper',
            name='database',
        ),
        migrations.AddField(
            model_name='database',
            name='paper',
            field=models.ManyToManyField(to='starrydata.Paper'),
        ),
    ]
