# Generated by Django 3.2.4 on 2021-06-29 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starrydata', '0008_auto_20210629_0354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='database',
            name='paper',
        ),
        migrations.AddField(
            model_name='paper',
            name='database',
            field=models.ManyToManyField(to='starrydata.Database'),
        ),
    ]
