# Generated by Django 3.2.4 on 2021-06-29 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starrydata', '0009_auto_20210629_0546'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('paper', models.ManyToManyField(to='starrydata.Paper')),
            ],
        ),
        migrations.CreateModel(
            name='Figure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('paper', models.ManyToManyField(to='starrydata.Paper')),
            ],
        ),
    ]
