# Generated by Django 3.2.4 on 2021-06-30 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starrydata', '0010_figure_sample'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='container_title',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='paper',
            name='publisher',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
