# Generated by Django 3.2.4 on 2021-07-07 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('starrydata', '0011_auto_20210630_0813'),
    ]

    operations = [
        migrations.CreateModel(
            name='PolymerTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PolymerTagTreeNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='starrydata.polymertagtreenode')),
                ('polymer_tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='starrydata.polymertag')),
            ],
        ),
    ]
