# Generated by Django 3.2.4 on 2021-07-14 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starrydata', '0012_polymernode_polymertag'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='polymernode',
            constraint=models.UniqueConstraint(fields=('polymer_tag', 'parent'), name='polymer_tag_unique'),
        ),
    ]
