# Generated by Django 3.2.4 on 2021-07-07 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('starrydata', '0012_polymertag_polymertagtreenode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polymertagtreenode',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='starrydata.polymertagtreenode'),
        ),
    ]
