# Generated by Django 3.2.4 on 2021-07-27 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('starrydata', '0013_alter_tag_name_en'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='synthesismethodtagtreenode',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='synthesismethodtagtreenode',
            name='synthesis_method_tag',
        ),
        migrations.DeleteModel(
            name='FabricationProcess',
        ),
        migrations.DeleteModel(
            name='SynthesisMethodTag',
        ),
        migrations.DeleteModel(
            name='SynthesisMethodTagTreeNode',
        ),
    ]
